language: rust
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo test --verbose
  - cargo bench
  - cargo run -- data/null.sl
env:
  - PROPTEST_CASES=8192
cache: cargo