[package]
name = "small-lang"
version = "0.1.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "small-lang"
required-features = ["structopt", "serde_json"]

[dependencies]
lazy_static = "~1"
seahash = "~3"
lalrpop-util = "0.16.3"
regex = "~1"
iter-set = "0.2.0"

[dependencies.structopt]
version = "0.2.14"
optional = true

[dependencies.mlsub]
git = "https://github.com/andrewhickman/mlsub-rs"
rev = "be53df8"

[dependencies.im]
package = "im-rc"
version = "~12"
features = ["serde"]

[dependencies.serde]
version = "1.0.101"
features = ["derive", "rc"]

[dependencies.serde_json]
version = "1.0.41"
optional = true

[build-dependencies]
lalrpop = "0.16.3"
